name: Expo Preview

on:
  pull_request:
    paths-ignore:
      - .requests/**
      - .github/**
      - .claude/**
jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
          # Use your own, or keep the automatically inferred branch name from `--auto`, when using different triggers.
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
